mysql_localhost:
  url: localhost
  username: root
  password: 123456
  port: 3306
  db: wdkl_member

mysql_39:
  url: 39.108.248.223
  username: root
  password: qwe123
  port: 3306
  db: wdkl_member